-- =============================================================================
-- RTS 운영 확인 쿼리
-- =============================================================================

-- 1) 최신 RULE_TIMEKEY (facid별 — infer 기본값)
SELECT MAX(RULE_TIMEKEY) AS MAX_RULE_TIMEKEY
  FROM RTS_LINEDSDB_INF
 WHERE FAC_ID = :facid;

-- 2) 학습 구간 후보 (최근 30일 — 앱에서 TRAIN_LOOKBACK_DAYS=30)
SELECT DISTINCT RULE_TIMEKEY
  FROM RTS_LINEDSDB_INF
 WHERE RULE_TIMEKEY >= TO_CHAR(SYSDATE - 30, 'YYYYMMDDHH24MISS') || '0000'
 ORDER BY RULE_TIMEKEY;

-- 3) 특정 timekey 입력 스냅샷 피벗 조회
SELECT RULE_TIMEKEY, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD, GBN_CD, ATTR_VAL
  FROM RTS_LINEDSDB_INF
 WHERE RULE_TIMEKEY = :rule_timekey
 ORDER BY PLAN_PROD_KEY, OPER_ID, GBN_CD;

-- 4) 추론 결과 — 가이드
SELECT RULE_TIMEKEY, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD,
       TARGET_EQP_CNT, GUIDE_SOURCE
  FROM RTS_GUIDE_INF
 WHERE RULE_TIMEKEY = :rule_timekey
 ORDER BY PLAN_PROD_KEY, OPER_ID;

-- 5) 추론 결과 — 동적 (계획달성 / 배치 / 전환)
SELECT EVENT_TM, PLAN_PROD_KEY, OPER_ID, PLAN_QTY, PRODUCE_QTY, ACHIEVE_RATE, EQP_UTIL_RATE
  FROM RTS_PLAN_ACHV_INF
 WHERE RULE_TIMEKEY = :rule_timekey
 ORDER BY EVENT_TM, PLAN_PROD_KEY;

SELECT EQP_ID, START_TIME, END_TIME, PLAN_PROD_KEY, OPER_ID, PRODUCE_QTY
  FROM RTS_ASSIGN_INF
 WHERE RULE_TIMEKEY = :rule_timekey
 ORDER BY EQP_ID, SEQ_NO;

SELECT EVENT_TM, EQP_ID, FROM_BATCH_ID, TO_BATCH_ID,
       FROM_PLAN_PROD_KEY, TO_PLAN_PROD_KEY
  FROM RTS_CONV_INF
 WHERE RULE_TIMEKEY = :rule_timekey
 ORDER BY EVENT_TM;
