-- RTS_GUIDE_INF/HIS
INSERT INTO {table} (
    RULE_TIMEKEY, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD,
    TARGET_EQP_CNT, GUIDE_SOURCE,
    CRT_TM, CRT_USER_ID
) VALUES (
    :RULE_TIMEKEY, :PLAN_PROD_KEY, :OPER_ID, :EQP_MODEL_CD,
    :TARGET_EQP_CNT, :GUIDE_SOURCE,
    SYSTIMESTAMP, :CRT_USER_ID
)
