-- RTS_CONV_INF/HIS
INSERT INTO {table} (
    RULE_TIMEKEY, EVENT_TM, EQP_ID, EQP_MODEL_CD, SEQ_NO,
    START_TIME, END_TIME,
    FROM_BATCH_ID, TO_BATCH_ID,
    FROM_PLAN_PROD_KEY, TO_PLAN_PROD_KEY,
    FROM_OPER_ID, TO_OPER_ID,
    CRT_TM, CRT_USER_ID
) VALUES (
    :RULE_TIMEKEY, :EVENT_TM, :EQP_ID, :EQP_MODEL_CD, :SEQ_NO,
    :START_TIME, :END_TIME,
    :FROM_BATCH_ID, :TO_BATCH_ID,
    :FROM_PLAN_PROD_KEY, :TO_PLAN_PROD_KEY,
    :FROM_OPER_ID, :TO_OPER_ID,
    SYSTIMESTAMP, :CRT_USER_ID
)
