-- RTS_EQPALLOCATION_HIS (EVENT_TIMEKEY = CRT_TM YYYYMMDDHH24MISS)
INSERT INTO {table} (
    FAC_ID, RULE_TIMEKEY, BATCH_ID, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD,
    TARGET_EQP_CNT, CUR_EQP_CNT, MODE_TYP,
    CRT_TM, CRT_USER_ID, EVENT_TIMEKEY
) VALUES (
    :FAC_ID, :RULE_TIMEKEY, :BATCH_ID, :PLAN_PROD_KEY, :OPER_ID, :EQP_MODEL_CD,
    :TARGET_EQP_CNT, :CUR_EQP_CNT, :MODE_TYP,
    SYSTIMESTAMP, :CRT_USER_ID,
    TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS')
)
