-- RTS_PLAN_ACHV_INF/HIS
INSERT INTO {table} (
    RULE_TIMEKEY, EVENT_TM, BATCH_ID, PLAN_PROD_KEY, OPER_ID,
    PLAN_QTY, REMAIN_QTY, PRODUCE_QTY, ACHIEVE_RATE, EQP_UTIL_RATE,
    CRT_TM, CRT_USER_ID
) VALUES (
    :RULE_TIMEKEY, :EVENT_TM, :BATCH_ID, :PLAN_PROD_KEY, :OPER_ID,
    :PLAN_QTY, :REMAIN_QTY, :PRODUCE_QTY, :ACHIEVE_RATE, :EQP_UTIL_RATE,
    SYSTIMESTAMP, :CRT_USER_ID
)
