-- =============================================================================
-- RTS 장비 스케줄링 RL — Oracle 테이블 생성
-- 실행: sqlplus user/pass@dsn @db/sql/reference/01_create_tables.sql
-- 출력 테이블 정리: 00_output_tables.md
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. 입력 스냅샷 (long-format, GBN_CD 피벗 → ProblemInstance)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_LINEDSDB_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_LINEDSDB_INF (
  RULE_TIMEKEY   VARCHAR2(16)   NOT NULL,
  FAC_ID         VARCHAR2(20)   NOT NULL,
  BATCH_ID       VARCHAR2(50)   NOT NULL,
  PLAN_PROD_KEY  VARCHAR2(50)   NOT NULL,
  OPER_ID        VARCHAR2(50)   NOT NULL,
  OPER_SEQ       NUMBER(5)      NOT NULL,
  EQP_MODEL_CD   VARCHAR2(50)   NOT NULL,
  GBN_CD         VARCHAR2(30)   NOT NULL,
  ATTR_VAL       VARCHAR2(100)  NOT NULL,
  CONSTRAINT PK_RTS_LINEDSDB_INF PRIMARY KEY (
    RULE_TIMEKEY, FAC_ID, BATCH_ID, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD, GBN_CD
  )
);

CREATE INDEX IX_LINEDSDB_RK ON RTS_LINEDSDB_INF (RULE_TIMEKEY);

COMMENT ON TABLE RTS_LINEDSDB_INF IS '입력 스냅샷. GBN_CD: EQUIP_UPH|ASSIGN_EQUIP_CNT|TOOL_QTY|EXEC_D0_PLAN|AVAIL_WIP_QTY';
COMMENT ON COLUMN RTS_LINEDSDB_INF.GBN_CD IS 'EQUIP_UPH, ASSIGN_EQUIP_CNT, TOOL_QTY, EXEC_D0_PLAN, AVAIL_WIP_QTY';

-- ---------------------------------------------------------------------------
-- 2. 가이드 배분 (Mode 1 · 재공 무한 목표 장비 대수 — RTS_EQPALLOCATION)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_EQPALLOCATION_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_EQPALLOCATION_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_GUIDE_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_GUIDE_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_EQPALLOCATION_INF (
  FAC_ID           VARCHAR2(50)   NOT NULL,
  RULE_TIMEKEY     VARCHAR2(16)   NOT NULL,
  BATCH_ID         VARCHAR2(50)   NOT NULL,
  PLAN_PROD_KEY    VARCHAR2(50)   NOT NULL,
  OPER_ID          VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD     VARCHAR2(50)   NOT NULL,
  TARGET_EQP_CNT   NUMBER(10)     NOT NULL,
  CUR_EQP_CNT      NUMBER(10)     NOT NULL,
  MODE_TYP         VARCHAR2(20)   NOT NULL,
  CRT_TM           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID      VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_RTS_EQPALLOCATION_INF PRIMARY KEY (
    RULE_TIMEKEY, FAC_ID, BATCH_ID, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD
  )
);

CREATE TABLE RTS_EQPALLOCATION_HIS (
  FAC_ID           VARCHAR2(50)   NOT NULL,
  RULE_TIMEKEY     VARCHAR2(16)   NOT NULL,
  BATCH_ID         VARCHAR2(50)   NOT NULL,
  PLAN_PROD_KEY    VARCHAR2(50)   NOT NULL,
  OPER_ID          VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD     VARCHAR2(50)   NOT NULL,
  TARGET_EQP_CNT   NUMBER(10)     NOT NULL,
  CUR_EQP_CNT      NUMBER(10)     NOT NULL,
  MODE_TYP         VARCHAR2(20)   NOT NULL,
  CRT_TM           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID      VARCHAR2(50)   NOT NULL,
  EVENT_TIMEKEY    VARCHAR2(14)   NOT NULL,
  CONSTRAINT PK_RTS_EQPALLOCATION_HIS PRIMARY KEY (
    RULE_TIMEKEY, FAC_ID, BATCH_ID, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD, EVENT_TIMEKEY
  )
);

COMMENT ON COLUMN RTS_EQPALLOCATION_INF.MODE_TYP IS 'RL | Heuristic';
COMMENT ON COLUMN RTS_EQPALLOCATION_INF.CUR_EQP_CNT IS '현재 배치 장비 수량 (init_assign)';

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_PLAN_ACHV_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_PLAN_ACHV_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ---------------------------------------------------------------------------
-- 3. 동적 운영 결과 — 장비 배치·생산 (eqp × hour)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_ASSIGN_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_ASSIGN_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_ASSIGN_INF (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EQP_ID          VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD    VARCHAR2(50)  NOT NULL,
  SEQ_NO          NUMBER(8)     NOT NULL,
  START_TIME      VARCHAR2(16)  NOT NULL,
  END_TIME        VARCHAR2(16)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_ASSIGN_INF PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO
  )
);

CREATE TABLE RTS_ASSIGN_HIS (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EQP_ID          VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD    VARCHAR2(50)  NOT NULL,
  SEQ_NO          NUMBER(8)     NOT NULL,
  START_TIME      VARCHAR2(16)  NOT NULL,
  END_TIME        VARCHAR2(16)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_ASSIGN_HIS PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO, CRT_TM
  )
);

-- ---------------------------------------------------------------------------
-- 4. 동적 운영 결과 — 장비 전환 계획 (RTS_EQPCONVPLAN)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_EQPCONVPLAN_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_EQPCONVPLAN_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_CONV_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_CONV_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_EQPCONVPLAN_INF (
  FAC_ID                 VARCHAR2(50)   NOT NULL,
  RULE_TIMEKEY           VARCHAR2(16)   NOT NULL,
  PRCS_STAT_CD           VARCHAR2(20)   NOT NULL,
  JOB_ID                 VARCHAR2(50)   NOT NULL,
  RTS_GBN_CD             VARCHAR2(20)   NOT NULL,
  EQP_ID                 VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD           VARCHAR2(50)   NOT NULL,
  TESTER_EQP_MODEL_CD    VARCHAR2(50)   NOT NULL,
  CONV_START_TM          VARCHAR2(12)   NOT NULL,
  CONV_END_TM            VARCHAR2(12)   NOT NULL,
  CONV_TIME              NUMBER(8)      NOT NULL,
  LOT_CD                 VARCHAR2(50)   NOT NULL,
  PRB_CARD_NO            VARCHAR2(50)   NOT NULL,
  TEMPER_VAL             VARCHAR2(50)   NOT NULL,
  PLAN_PROD_ATTR_VAL     VARCHAR2(200)  NOT NULL,
  TO_LOT_CD              VARCHAR2(50)   NOT NULL,
  TO_PRB_CARD_NO         VARCHAR2(50)   NOT NULL,
  PRB_CARD_NO_LVAL       VARCHAR2(50)   NOT NULL,
  TO_TEMPER_VAL          VARCHAR2(50)   NOT NULL,
  TO_PLAN_PROD_ATTR_VAL  VARCHAR2(200)  NOT NULL,
  REASON_CD              VARCHAR2(20)   NOT NULL,
  REASON_CTN             VARCHAR2(500)  NOT NULL,
  TRANSMIT_YN            VARCHAR2(1)    NOT NULL,
  TRANSMIT_TM            VARCHAR2(50),
  CRT_TM                 DATE           DEFAULT SYSDATE NOT NULL,
  CRT_USER_ID            VARCHAR2(50)   NOT NULL,
  CHG_TM                 DATE           DEFAULT SYSDATE NOT NULL,
  CHG_USER_ID            VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_RTS_EQPCONVPLAN_INF PRIMARY KEY (RULE_TIMEKEY, JOB_ID)
);

CREATE TABLE RTS_EQPCONVPLAN_HIS (
  FAC_ID                 VARCHAR2(50)   NOT NULL,
  RULE_TIMEKEY           VARCHAR2(16)   NOT NULL,
  PRCS_STAT_CD           VARCHAR2(20)   NOT NULL,
  JOB_ID                 VARCHAR2(50)   NOT NULL,
  RTS_GBN_CD             VARCHAR2(20)   NOT NULL,
  EQP_ID                 VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD           VARCHAR2(50)   NOT NULL,
  TESTER_EQP_MODEL_CD    VARCHAR2(50)   NOT NULL,
  CONV_START_TM          VARCHAR2(12)   NOT NULL,
  CONV_END_TM            VARCHAR2(12)   NOT NULL,
  CONV_TIME              NUMBER(8)      NOT NULL,
  LOT_CD                 VARCHAR2(50)   NOT NULL,
  PRB_CARD_NO            VARCHAR2(50)   NOT NULL,
  TEMPER_VAL             VARCHAR2(50)   NOT NULL,
  PLAN_PROD_ATTR_VAL     VARCHAR2(200)  NOT NULL,
  TO_LOT_CD              VARCHAR2(50)   NOT NULL,
  TO_PRB_CARD_NO         VARCHAR2(50)   NOT NULL,
  PRB_CARD_NO_LVAL       VARCHAR2(50)   NOT NULL,
  TO_TEMPER_VAL          VARCHAR2(50)   NOT NULL,
  TO_PLAN_PROD_ATTR_VAL  VARCHAR2(200)  NOT NULL,
  REASON_CD              VARCHAR2(20)   NOT NULL,
  REASON_CTN             VARCHAR2(500)  NOT NULL,
  TRANSMIT_YN            VARCHAR2(1)    NOT NULL,
  TRANSMIT_TM            VARCHAR2(50),
  CRT_TM                 DATE           DEFAULT SYSDATE NOT NULL,
  CRT_USER_ID            VARCHAR2(50)   NOT NULL,
  CHG_TM                 DATE           DEFAULT SYSDATE NOT NULL,
  CHG_USER_ID            VARCHAR2(50)   NOT NULL,
  EVENT_TIMEKEY          VARCHAR2(14)   NOT NULL,
  CONSTRAINT PK_RTS_EQPCONVPLAN_HIS PRIMARY KEY (RULE_TIMEKEY, JOB_ID, EVENT_TIMEKEY)
);

COMMIT;
