-- =============================================================================
-- RTS 장비 스케줄링 RL — Oracle 테이블 생성
-- 실행: sqlplus user/pass@dsn @db/sql/01_create_tables.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. 입력 스냅샷 (long-format, GBN_CD 피벗 → ProblemInstance)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_LINEDSDB_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_LINEDSDB_INF (
  RULE_TIMEKEY   VARCHAR2(16)   NOT NULL,
  FAC_ID         VARCHAR2(20)   NOT NULL,
  BATCH_ID       VARCHAR2(50)   NOT NULL,
  PLAN_PROD_KEY  VARCHAR2(50)   NOT NULL,
  OPER_ID        VARCHAR2(50)   NOT NULL,
  OPER_SEQ       NUMBER(5)      NOT NULL,
  EQP_MODEL_CD   VARCHAR2(50)   NOT NULL,
  GBN_CD         VARCHAR2(30)   NOT NULL,
  ATTR_VAL       VARCHAR2(100)  NOT NULL,
  CONSTRAINT PK_RTS_LINEDSDB_INF PRIMARY KEY (
    RULE_TIMEKEY, FAC_ID, BATCH_ID, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD, GBN_CD
  )
);

CREATE INDEX IX_LINEDSDB_RK ON RTS_LINEDSDB_INF (RULE_TIMEKEY);

COMMENT ON TABLE RTS_LINEDSDB_INF IS '입력 스냅샷. GBN_CD: EQUIP_UPH|ASSIGN_EQUIP_CNT|TOOL_QTY|D0_TARGET_QTY|AVAIL_WIP_QTY';
COMMENT ON COLUMN RTS_LINEDSDB_INF.GBN_CD IS 'EQUIP_UPH, ASSIGN_EQUIP_CNT, TOOL_QTY, D0_TARGET_QTY, AVAIL_WIP_QTY';

-- ---------------------------------------------------------------------------
-- 2. 가이드 배분 (Mode 1 · 재공 무한 목표 장비 대수)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_GUIDE_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_GUIDE_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_GUIDE_INF (
  RULE_TIMEKEY     VARCHAR2(16)   NOT NULL,
  PLAN_PROD_KEY    VARCHAR2(50)   NOT NULL,
  OPER_ID          VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD     VARCHAR2(50)   NOT NULL,
  TARGET_EQP_CNT   NUMBER(10,4)   NOT NULL,
  GUIDE_SOURCE     VARCHAR2(20)   NOT NULL,
  CRT_TM           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID      VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_RTS_GUIDE_INF PRIMARY KEY (
    RULE_TIMEKEY, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD
  )
);

CREATE TABLE RTS_GUIDE_HIS (
  RULE_TIMEKEY     VARCHAR2(16)   NOT NULL,
  PLAN_PROD_KEY    VARCHAR2(50)   NOT NULL,
  OPER_ID          VARCHAR2(50)   NOT NULL,
  EQP_MODEL_CD     VARCHAR2(50)   NOT NULL,
  TARGET_EQP_CNT   NUMBER(10,4)   NOT NULL,
  GUIDE_SOURCE     VARCHAR2(20)   NOT NULL,
  CRT_TM           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID      VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_RTS_GUIDE_HIS PRIMARY KEY (
    RULE_TIMEKEY, PLAN_PROD_KEY, OPER_ID, EQP_MODEL_CD, CRT_TM
  )
);

COMMENT ON COLUMN RTS_GUIDE_INF.GUIDE_SOURCE IS 'ANALYTIC | ALLOC_RL';

-- ---------------------------------------------------------------------------
-- 3. 동적 운영 결과 — 계획/달성 (task × hour)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_PLAN_ACHV_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_PLAN_ACHV_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_PLAN_ACHV_INF (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EVENT_TM        VARCHAR2(16)  NOT NULL,
  BATCH_ID        VARCHAR2(50)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PLAN_QTY        NUMBER(12)    NOT NULL,
  REMAIN_QTY      NUMBER(12)    NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  ACHIEVE_RATE    NUMBER(8,4)   NOT NULL,
  EQP_UTIL_RATE   NUMBER(8,4)   NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_PLAN_ACHV_INF PRIMARY KEY (
    RULE_TIMEKEY, EVENT_TM, BATCH_ID, PLAN_PROD_KEY, OPER_ID
  )
);

CREATE TABLE RTS_PLAN_ACHV_HIS (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EVENT_TM        VARCHAR2(16)  NOT NULL,
  BATCH_ID        VARCHAR2(50)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PLAN_QTY        NUMBER(12)    NOT NULL,
  REMAIN_QTY      NUMBER(12)    NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  ACHIEVE_RATE    NUMBER(8,4)   NOT NULL,
  EQP_UTIL_RATE   NUMBER(8,4)   NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_PLAN_ACHV_HIS PRIMARY KEY (
    RULE_TIMEKEY, EVENT_TM, BATCH_ID, PLAN_PROD_KEY, OPER_ID, CRT_TM
  )
);

-- ---------------------------------------------------------------------------
-- 4. 동적 운영 결과 — 장비 배치·생산 (eqp × hour)
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_ASSIGN_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_ASSIGN_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_ASSIGN_INF (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EQP_ID          VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD    VARCHAR2(50)  NOT NULL,
  SEQ_NO          NUMBER(8)     NOT NULL,
  START_TIME      VARCHAR2(16)  NOT NULL,
  END_TIME        VARCHAR2(16)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_ASSIGN_INF PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO
  )
);

CREATE TABLE RTS_ASSIGN_HIS (
  RULE_TIMEKEY    VARCHAR2(16)  NOT NULL,
  EQP_ID          VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD    VARCHAR2(50)  NOT NULL,
  SEQ_NO          NUMBER(8)     NOT NULL,
  START_TIME      VARCHAR2(16)  NOT NULL,
  END_TIME        VARCHAR2(16)  NOT NULL,
  PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  OPER_ID         VARCHAR2(50)  NOT NULL,
  PRODUCE_QTY     NUMBER(12)    NOT NULL,
  CRT_TM          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID     VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_ASSIGN_HIS PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO, CRT_TM
  )
);

-- ---------------------------------------------------------------------------
-- 5. 동적 운영 결과 — batch(tool) 전환
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_CONV_INF PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RTS_CONV_HIS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE RTS_CONV_INF (
  RULE_TIMEKEY         VARCHAR2(16)  NOT NULL,
  EVENT_TM             VARCHAR2(16)  NOT NULL,
  EQP_ID               VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD         VARCHAR2(50)  NOT NULL,
  SEQ_NO               NUMBER(8)     NOT NULL,
  START_TIME           VARCHAR2(16)  NOT NULL,
  END_TIME             VARCHAR2(16)  NOT NULL,
  FROM_BATCH_ID        VARCHAR2(50)  NOT NULL,
  TO_BATCH_ID          VARCHAR2(50)  NOT NULL,
  FROM_PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  TO_PLAN_PROD_KEY     VARCHAR2(50)  NOT NULL,
  FROM_OPER_ID         VARCHAR2(50)  NOT NULL,
  TO_OPER_ID           VARCHAR2(50)  NOT NULL,
  CRT_TM               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID          VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_CONV_INF PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO
  )
);

CREATE TABLE RTS_CONV_HIS (
  RULE_TIMEKEY         VARCHAR2(16)  NOT NULL,
  EVENT_TM             VARCHAR2(16)  NOT NULL,
  EQP_ID               VARCHAR2(50)  NOT NULL,
  EQP_MODEL_CD         VARCHAR2(50)  NOT NULL,
  SEQ_NO               NUMBER(8)     NOT NULL,
  START_TIME           VARCHAR2(16)  NOT NULL,
  END_TIME             VARCHAR2(16)  NOT NULL,
  FROM_BATCH_ID        VARCHAR2(50)  NOT NULL,
  TO_BATCH_ID          VARCHAR2(50)  NOT NULL,
  FROM_PLAN_PROD_KEY   VARCHAR2(50)  NOT NULL,
  TO_PLAN_PROD_KEY     VARCHAR2(50)  NOT NULL,
  FROM_OPER_ID         VARCHAR2(50)  NOT NULL,
  TO_OPER_ID           VARCHAR2(50)  NOT NULL,
  CRT_TM               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_USER_ID          VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RTS_CONV_HIS PRIMARY KEY (
    RULE_TIMEKEY, EQP_ID, SEQ_NO, CRT_TM
  )
);

COMMIT;
