-- RTS_EQPCONVPLAN_INF
INSERT INTO {table} (
    FAC_ID, RULE_TIMEKEY, PRCS_STAT_CD, JOB_ID, RTS_GBN_CD,
    EQP_ID, EQP_MODEL_CD, TESTER_EQP_MODEL_CD,
    CONV_START_TM, CONV_END_TM, CONV_TIME,
    LOT_CD, PRB_CARD_NO, TEMPER_VAL, PLAN_PROD_ATTR_VAL,
    TO_LOT_CD, TO_PRB_CARD_NO, PRB_CARD_NO_LVAL, TO_TEMPER_VAL, TO_PLAN_PROD_ATTR_VAL,
    REASON_CD, REASON_CTN, TRANSMIT_YN, TRANSMIT_TM,
    CRT_TM, CRT_USER_ID, CHG_TM, CHG_USER_ID
) VALUES (
    :FAC_ID, :RULE_TIMEKEY, :PRCS_STAT_CD, :JOB_ID, :RTS_GBN_CD,
    :EQP_ID, :EQP_MODEL_CD, :TESTER_EQP_MODEL_CD,
    :CONV_START_TM, :CONV_END_TM, :CONV_TIME,
    :LOT_CD, :PRB_CARD_NO, :TEMPER_VAL, :PLAN_PROD_ATTR_VAL,
    :TO_LOT_CD, :TO_PRB_CARD_NO, :PRB_CARD_NO_LVAL, :TO_TEMPER_VAL, :TO_PLAN_PROD_ATTR_VAL,
    :REASON_CD, :REASON_CTN, :TRANSMIT_YN, :TRANSMIT_TM,
    SYSTIMESTAMP, :CRT_USER_ID, SYSTIMESTAMP, :CHG_USER_ID
)
