-- RTS_ASSIGN_INF/HIS
INSERT INTO {table} (
    RULE_TIMEKEY, EQP_ID, EQP_MODEL_CD, SEQ_NO,
    START_TIME, END_TIME, PLAN_PROD_KEY, OPER_ID, PRODUCE_QTY,
    CRT_TM, CRT_USER_ID
) VALUES (
    :RULE_TIMEKEY, :EQP_ID, :EQP_MODEL_CD, :SEQ_NO,
    :START_TIME, :END_TIME, :PLAN_PROD_KEY, :OPER_ID, :PRODUCE_QTY,
    SYSTIMESTAMP, :CRT_USER_ID
)
